### ISSUE TITLE
credentials

### ISSUE THREAD

**Issue by johnwmillr** [michaelmilleryoder/reddit_project#1]
If you're worried about this sort of thing, you might want to remove your credentials from the scrape_reddit.py file! Store them in a secret.txt file you include in your .gitignore file. Otherwise I may just masquerade as michaelmilleryoder on reddit!

**Comment by michaelmilleryoder** [comment]
Wow, thanks for catching that! I didn't think anyone was looking at this code :)

**Comment by johnwmillr** [comment]
I'm *always* watching :)
